### PR TITLE
fix: for ore generation

### LINKED ISSUE #4523: No ore generation in Josharias Survival
**Problem:** With no ores being generated in the world of JS big parts of the tech tree are unavailble, reducing the scope of the game play module drastically. This is a regression compared to previouls (preview) releases.

The ore gen was working in **preview 1123 (20210103)**, so it's likely related to our JOML migration effort. Based on that date and the involved modules, this (most likely) boils down to:

- https://github.com/Terasology/CustomOreGen/compare/93210238ccfd50dde2a6d22776a072db2ac47c11..develop
- https://github.com/Terasology/OreGeneration/compare/1144f6197cc36eed928e02d0ebe38e41f886eb0a..develop

### PR DESCRIPTION
**Pull request by pollend**
This addresses the AABB bounds but I'm not so sure about the translation on line 78. I don't think that is a actually a translation. multiplying. for generating structures it expects the transformed location to be a local transform relative to the chunk from what I can tell. 

```
m00 * x + m10 * y + m20 * z = m30
m01 * x + m11 * y + m21 * z = m31
m02 * x + m12 * y + m22 * z = m32
m03 * x + m13 * y + m23 * z = m33
```

Fixes https://github.com/MovingBlocks/Terasology/issues/4523

### CODE REVIEW

**Comment by skaldarnar** [comment]
Honestly, I can't follow on the details here :see_no_evil: unfortunately, this does not fix the problem (yet).

**Review by 4Denthusiast — DISMISSED** [review]
This looks fine. `min` and `max` might as well be dropped in favor of just using `aabb` directly though.

File: src/main/java/org/terasology/customOreGen/PocketStructureDefinition.java [hunk 1]
```diff
@@ -163,9 +167,9 @@ public void generateStructure(StructureCallback callback) {
             minNoisyR2 *= minNoisyR2;
             // iterate through blocks
             Vector4f pos = new Vector4f();
-            for (int x = Math.max(0, minPosition.x()); x <= Math.min(chunkSize.x() - 1, maxPosition.x()); x++) {
-                for (int y = Math.max(0, minPosition.y()); y <= Math.min(chunkSize.y() - 1, maxPosition.y()); y++) {
-                    for (int z = Math.max(0, minPosition.z()); z <= Math.min(chunkSize.z() - 1, maxPosition.z()); z++) {
+            for (int x =  minPosition.x(); x <=  maxPosition.x(); x++) {
```
Comment (4Denthusiast) [inline src/main/java/org/terasology/customOreGen/PocketStructureDefinition.java:170]: It's fine to have the coordinates exceeding the bounds of the chunk, but if they exceed the bounds of the facet's borders, it will cause an exception.

**Review by 4Denthusiast — CHANGES_REQUESTED** [review]

File: src/main/java/org/terasology/customOreGen/PocketStructureDefinition.java (hunk 1 above)
Comment (pollend) [reply src/main/java/org/terasology/customOreGen/PocketStructureDefinition.java:170]: It applies an inverse matrix to map them from global to local space. we need to clip it at the end right?

**Review by 4Denthusiast — APPROVED** [review]
